package com.OSC.Academy.models.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
//table name in DB
@Table(name="clients")

public class Client implements Serializable {
	
	@Id
	//id is generated by way incremental in MYSQL
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@NotEmpty(message = "No puede estar vacio")
	@Size(min=4, max=12, message = "El tamaño tiene qu estar entre 4 y 12 ")
	@Column(nullable=false)
	private String name;
	
	@NotEmpty(message = "No puede estar vacio")
	private String lastName;
	
	@Column(nullable=false, unique=true)
	@NotEmpty(message = "No puede estar vacio")
	@Email(message = "Tiene que tener el formato correcto")
	private String email;
	
	//if column name is equal to attribute, its can be to skip
	@NotNull(message = "No puede estar vacio")
	@Column(name="create_at")
	@Temporal(TemporalType.DATE)
	private Date createAt;
	
	private String image;
	
	//@PrePersist
	//public void prePersist() {
		//createAt = new Date();
	//}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreateAt() {
		return createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}
	
	
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

}
